#!/usr/bin/env bash
# Install nginx on your web-01
# When querying Nginx at its root / with a GET request using curl,
# it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '24i\       rewrite ^/redirect_me https://youtu.be/-eSpiwGcW2k?si=QwpDiJcvzbZMnCnj permanent;' /etc/nginx/sites-available/default

sudo service nginx start
