#!/usr/bin/env bash
# Install nginx on your web-01
# When querying Nginx at its root / with a GET request using curl,
# it must return a page that contains the string Hello World!
# configure the server not found status

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html';
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.linkedin.com/in/mahmoud-hamdy-8b6825245/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i "46i error_page 404 /custom_404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
