#!/usr/bin/env bash
# Nginx must be running, and listening on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
kill -9 "$(cat /var/run/nginx.pid)"
