#!/usr/bin/env bash
# Bash script that displays Best School 10 times.

min=1;
hour=0;

while [ $hour -le 12 ]
do
    echo "Hour : $hour"
    while [ $min -le 59 ]
    do
        echo $min
        ((min++))
    done
    min=1
    ((hour++))
done
